apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: eawebapi
  name: eawebapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eawebapi
      color: green
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: eawebapi
        color: green
    spec:
      containers:
      - image: nginx
        name: eawebapi