apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: eawebapi
  name: eawebapi-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 31500
  selector:
    app: eawebapi
    color: green
  type: NodePort